# Generated by Django 3.1.5 on 2021-11-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="test",
            new_name="text",
        ),
    ]
